FROM kodekloud-lab:base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    docker.io \
    docker-compose \
    && rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker user

USER user

CMD ["/bin/bash"]
